### ISSUE TITLE
missing list tables

### ISSUE THREAD

**Issue by matteoredaelli** [elbosso/openldap-jdbcldap#1]
Hello

I was able to connect to Active directory with dbeaver

jdbc:ldap://dmc1.redaelli.org/DC=group,DC=redaelli,DC=org?SEARCH_SCOPE:=subTreeScope&concat_atts:=true

and run some queries but I cannot see a "table" list (I support a list of dn=ou=X, ...)

Regards
Matteo

**Comment by elbosso** [comment]
Can you please elaborate on that - because that was what led me to branching this project in the first place and in my tests it worked. Could you therefore please explain what you mean by I support a list of dn=ou=X, ...? The driver needs to be told where to look for "tables" by specifying a text file containing lines like for example:
```
numTables=2
table.1.ocs=inetOrgPerson
table.1.base=ou=people,dc=planetexpress,dc=com
table.0.scope=subTreeScope
table.0.ocs=inetOrgPerson
table.0.name=PlanetExpressGroups
table.1.scope=subTreeScope
table.0.base=ou=groups,dc=planetexpress,dc=com
table.1.name=PlanetExpressPeople
```
The JDBC driver then needs to be informed about this file by setting the connection property `table_def` to the full filename of that file. I know that is cumbersome, but for me - it worked really well. I also wrote about this [here](https://elbosso.github.io/sqlshell_support_ldap_ii.html#content) (sorry, only in german) and you can see in the screenshots that there are two tables there...

The "Pseudo"-tables that are created that way can be used in SQL statements like any other "real" table - also from [here](https://elbosso.github.io/sqlshell_support_ldap_ii.html#content):
Instead of having to type 
```
SELECT dn, mail FROM subTreeScope;ou=people,dc=planetexpress,dc=com
```
you can simply type
```
SELECT dn, mail FROM PlanetExpressPeople
```
to get the same result (these samples assume the content of [this](https://github.com/elbosso/docker-test-openldap) docker image for testing purposes - master branch)...

[Here](http://myvd.sourceforge.net/bridge.html) is the originating official documentation for this feature...

**Comment by matteoredaelli** [comment]
Ok thanks!

Good, I'll use your suggestion for getting table list.

Thanks
Matteo
